name=Soldered-Button-LED-Buzzer-Board
version=1.0.0
author=Fran Fodor
maintainer=Fran Fodor <fran.fodor@soldered.com>
sentence=Arduino library for Soldered Button, LED & Buzzer Board
paragraph=Control WS2812B LEDs and passive buzzer, read button states via I2C. Designed for the Soldered Button LED Buzzer Board with ATtiny404 firmware.
category=Other
url=https://www.soldered.com/
repository=https://github.com/SolderedElectronics/Soldered-Button-LED-Buzzer-Board-Arduino-Library
architectures=*
includes=ButtonLedBuzzerBoard-SOLDERED.h
